### ISSUE TITLE
Show progress for each show being copied/moved

### ISSUE THREAD

**Issue by oddoye-david** [oddoye-david/shogan#3]
Progress for each show being moved/copied should be shown out of a 100%.

**Comment by silentworks** [comment]
Maybe we can use a library like https://github.com/sindresorhus/cpy which has progress reporting. We would need to test if we speed is impacted drastically by using this.

**Comment by oddoye-david** [comment]
Yeah. I want to take a shot at implementing it myself first. If i fall face first, i'll reach for the lib. Ful steam ahead with the streams!!! This should be fun

**Comment by oddoye-david** [comment]
Nailed it.
